# save/load settings
filename_saved        :  C:/science/students/Golinskaya/july080726_CO_SB.spv 
work_folder           :  C:/science/students/Golinskaya 
plot_set_folder       :  C:/science/Noterdaeme/J0800+3051 
SDSSfolder            :  C:/science/Noterdaeme/H2/Intervening 
SDSSDR14              :  D:/science/sdss/DR14/dr14.hdf5
SDSSLeefolder         :  C:/science/SDSS/DR9_Lee/BOSSLyaDR9_spectra/ 
XQ100folder           :  C:/science/QSO/XQ100/
P94folder             :  C:/science/QSO/XShooter/P94/
VandelsFile           :  C:/science/QSO/VANDELS/Vandels.csv
KodiaqFile            :  C:/science/QSO/KODIAQ_DR2/catalog.dat   
UVESfolder            :  C:/science/QSO/Q_spec/
ErositaSDSSFile       :  C:/science/Erosita/UV_Xray/match2_DR14Q_add.csv
ErositaDESIFile       :  D:/DESI/erosita_DESI_cat.csv
MALSfolder            :  C:/science/Gupta/MALS/HI_gal/
QMOSTfolder           :  D:/PAQS/best_spectra/
#ErositaFile           :  C:/science/Erosita/UV_Xray/individual/individual_targets.csv
IGMspecFile           :  C:/science/QSO/igmspec_db_v02.hdf5
SFDMapPath            :  C:/science/data/sfddata-master
Lyasamplefile         :  C:/science/Telikova/Lyasample/sample.dat
loadfile              :  C:/science/python/sload.py

# preferences
developerMode         :  True
blindMode             :  False 
display               :  1 
specview              :  steperr 
selectview            :  regions 
linelabels            :  short 
showinactive          :  True 
show_osc              :  True 
juliaFit              :  True 
fitType               :  julia 
fitComp               :  True 
fit_method            :  LsqFit.lmfit 
fit_tolerance         :  0.0001 
fitview               :  line 
telluric              :  True 
show_residuals        :  True 
show_2d               :  False 
num_between           :  7 
tau_limit             :  0.01 
accuracy              :  0.05 
julia_grid            :  uniform 
julia_grid_num        :  3 
julia_binned          :  True 
comp_view             :  all 
animateFit            :  False 
polyDeg               :  39 
SDSScat               :  Astroquery 
fullscreen            :  False 

# plot figure options 
width                 :  14.0 
height                :  18.0 
rows                  :  11 
cols                  :  1 
order                 :  v 
v_indent              :  0.04 
h_indent              :  0.03 
col_offset            :  0.015 
row_offset            :  0.015 
units                 :  l 
regions               :  0 
xmin                  :  -85.0 
xmax                  :  -47.0 
ymin                  :  -0.1 
ymax                  :  1.2 
z_ref                 :  4.09607362 
sys_ind               :  0 
spec_lw               :  1.0 
spec_color            :  255 
show_err              :  1 
error_cap             :  0.0 
show_telluric         :  1 
tell_color            :  2863333375 
telluric_fill         :  1 
telluric_lw           :  0.4 
residuals             :  0 
gray_out              :  0 
res_sigma             :  2 
fit_color             :  2852126975 
fit_lw                :  2.0 
fit_ls                :  solid 
res_style             :  step 
res_color             :  4289331455 
show_disp             :  0 
disp_alpha            :  0.3 
show_comps            :  0 
comp_lw               :  0.5 
comp_ls               :  solid 
grad_fill             :  1 
grad_fill_comps       :  1 
grad_fill_up          :  0.0 
grad_fill_down        :  0.3 
comp_colors           :  4289331455, 748694783, 4286516991, 2489826815 
show_species_colors   :  1 
species_colors        :  3435921663, 3434283263, 3432775935, 3431142655, 3429641471, 3428075007, 3426442751, 3424876031, 3423309567, 3422594559, 2863333375 
font                  :  Times New Roman 
font_size             :  16 
xlabel                :  Observed wavelength ($\rm \AA$) 
ylabel                :  Normalised Flux 
x_ticks               :  10.0 
xnum                  :  10 
y_ticks               :  0.5 
ynum                  :  5 
title                 :   
show_title            :  0 
font_title            :  16 
title_x_pos           :  0.95 
title_y_pos           :  0.9 
show_labels           :  1 
font_labels           :  16 
labels_corr           :  1 
name_x_pos            :  0.03 
name_y_pos            :  0.75 
indlines_ls           :  dashed 
indlines_lw           :  1.0 
add_lines             :  -65.34 
addlines_ls           :  dotted 
add_short             :  1 
add_full              :  0 
plotfile              :  C:/science/Noterdaeme/J0800+3051/J08H2norm_new.pdf 
show_H2               :   
only_marks            :  0 
all_comps_marks       :  0 
pos_H2                :  1.0 
show_cont             :  1 
corr_cheb             :  1 
show_cf               :  1 
cfs                   :  cf0 
show_cf_value         :  1 
cf_color              :  1437204735 
over_file             :   
over_color            :  11206655 

# snapshot figure options
snap_width            :  20.0 
snap_height           :  5.0 
snap_x_ticks          :  10.0 
snap_xnum             :  10 
snap_y_ticks          :  10.0 
snap_ynum             :  4 
snap_font             :  34 
snap_ylabel           :  Flux 
snap_xlabel           :  Wavelength 

# MCMC fit options
MCMC_sampler          :  Affine 
MCMC_walkers          :  300 
MCMC_iters            :  2000 
MCMC_threads          :  25 
MCMC_thinning         :  1 
MCMC_burnin           :  2500 
MCMC_graph            :  chainConsumer 
MCMC_smooth           :  True 
MCMC_truths           :  None 
MCMC_likelihood       :  True 
MCMC_cutlikelihood    :  50 
MCMC_disp_num         :  200 
 
# generate abs options
gen_template          :  const 
gen_z                 :  0.0 
gen_xmin              :  3800.0 
gen_xmax              :  6000.0 
gen_resolution        :  140000.0 
gen_lyaforest         :  0.0 
gen_Av                :  0.0 
gen_z_Av              :  0.0 
gen_snr               :  0.0 
gen_num               :  500 
gen_tau               :  0.002 

# color-color options
traceNum              :  5 
z_em_min              :  4.67 
z_em_max              :  4.67 
z_abs_min             :  4.1 
z_abs_max             :  4.1 
HI_min                :  20 
HI_max                :  22.0 
H2_min                :  20 
H2_max                :  22.5 
Av_min                :  0 
Av_max                :  2 
Av_bump_min           :  2 
Av_bump_max           :  2

# erosita options
ero_x_axis            :  L_UV_corr 
ero_y_axis            :  L_UV_ext 
ero_c_axis            :  L_UV 
ero_colnames          :  SDSS_NAME PLATE FIBERID z JMAG JFLUX R bbb_slope 
ero_lUV               :  2500.0 
ero_tempmin           :  320.0 
ero_tempmax           :  5000.0 
ero_hosts             :  S0 Sa Sb Sc Ell2 Ell5 Ell13 
ero_filters           :  FUV NUV u g r i z Y J H K W1 W2 W3 W4 